# Generated by Django 2.2 on 2019-05-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='pic_url',
            field=models.URLField(blank=True),
        ),
    ]
