# Generated by Django 2.2 on 2019-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190430_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayroute',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='pic_url',
            field=models.URLField(),
        ),
    ]
