# Generated by Django 2.2 on 2019-05-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190430_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroute',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
