# Generated by Django 2.2 on 2019-05-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_dayroute_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='thumbs/'),
        ),
    ]
