# Generated by Django 2.2 on 2019-05-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_instapost_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='instapost',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
