# Generated by Django 2.2 on 2019-05-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20190430_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='json_backups/'),
        ),
    ]
