# Generated by Django 2.2 on 2019-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20190501_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='thumb_url',
            field=models.URLField(null=True),
        ),
    ]
