# Generated by Django 2.2 on 2019-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_instapost_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep', models.BooleanField()),
                ('post_id', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
