# Generated by Django 2.2 on 2019-05-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_dayroute_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayroute',
            name='gps_file',
            field=models.FileField(blank=True, upload_to='gps_files/'),
        ),
    ]
