# Generated by Django 2.2 on 2019-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20190508_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='uploader_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instapost',
            name='uploader_profile_url',
            field=models.URLField(null=True),
        ),
    ]
