# Generated by Django 2.2 on 2019-05-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20190509_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instapost',
            old_name='uploader_profile_url',
            new_name='uploader_profile',
        ),
    ]
