# Generated by Django 2.2 on 2019-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20190509_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroute',
            name='journal_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='thumb_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
