# Generated by Django 2.2 on 2019-05-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20190512_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayroute',
            old_name='journal_text',
            new_name='day_text',
        ),
        migrations.RemoveField(
            model_name='dayroute',
            name='rest_day_text',
        ),
    ]
