# Generated by Django 3.2.6 on 2021-09-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20210820_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='post_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postrecord',
            name='post_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
